
[colors]
# BACKGROUNDS #
bgBlueGrey = #1D1B29
bgTransparent = #00000000
dg1 = #363636
# URGENT #
urgOrange = #F7C84F

# Group 1 #
orange = #FFE699
blue = #99B3FF
# Group 2 #
offOrange = #E3CE8F
offBlue = #EFCEE3
# CURRENT #
bg = ${colors.bgBlueGrey}
main = ${colors.dg1}

hightlight = ${colors.orange}
dimHighlight = ${colors.offOrange}

urgent = ${colors.urgOrange}


[fonts]
firaMono1 = "FiraMono Nerd Font:size=20" 
firaMono2 = "FiraMono Nerd Font:size=17"
firaMono3 = "FiraMono Nerd Font:size=15"
# CURRENT #
larger= ${fonts.firaMono1}
main = ${fonts.firaMono2}
smaller = ${fonts.firaMono3} 

[bar/center]
# VISUALS #
border-color = ${colors.main}
background = ${colors.bgTransparent}
foreground = ${colors.main}
# FONTS #
font-0 = ${fonts.main}
font-1 = ${fonts.smaller}
font-2 = ${fonts.larger}
# UNDERLINE #
underline-color = ${colors.main}
underline-size = 3
# BORDERS #
border-size = 0
radius = 0

width = 30%
height = 30
offset-x = 35%
offset-y = 0

bottom = true
override-redirect = true
wm-restack = ewmh
fixed-center = true

# MODULES #
modules-center = i3
modules-right = time spacer spacer2
modules-left = spacer2 date
[settings]
screenchange-reload = true
pseudo-transparency = false

[module/date]
format-foreground = ${colors.dimHighlight}
format-underline = ${colors.main}
label-font = 2

type = internal/date
interval = 500
date = %b %d

[module/time]
format-foreground = ${colors.dimHighlight}
format-underline = ${colors.main}
label-font = 2
label-offset = 20

type = internal/date
interval = 60
date = %H:%M  

[module/i3]
# FOCUSED #
label-focused-foreground = ${colors.hightlight}
label-focused-font = 3
# URGENT #
label-urgent-foreground = ${colors.urgent}
label-urgent-underline = ${colors.urgent}
# SEPERATOR #
label-separator-foreground = ${colors.main}
format-underline = ${colors.main}

label-separator = |
label-separator-padding = 0

type = internal/i3
enable-click = false
enable-scroll = false
wrapping-scroll = false

format = <label-state>
label-focused = %name%
label-unfocused = %name%
label-visible = %name%
label-urgent = %name%

[module/spacer]
type = custom/text
content = " "
content-padding = 0
[module/spacer2]
type = custom/text
content = " "
content-padding = 2
[module/spacer3]
type = custom/text
content = "         "
content-padding = 2

