
# OPACITY
active-opacity = 1;
inactive-opacity = 0.9;

# OPACITY OVERRIDES
opacity-rule = [
	"100:class_g = 'librewolf'"
	"100:class_g = 'steam_app_0'"
	"90:class_g = 'legcord'"
	"80:class_g = 'kitty'"
];
