
# COLORS #
background #1D1B29
foreground #FFFFD4

background_opacity 1

cursor_shape beam
cursor_blink_interval 0.5

# FONTS #
font_family FiraMono Nerd Font
font_size 14

# REMOVE QUIT CONFIRMATION PROMPT #
confirm_os_window_close 0 

# PADDING #
#top right bottom left
#window_padding_width 0 0 0 0
