
[colors]
white = #FFFFFF
whiteYellow = #FFFEE5
blue0 = #7489D4
blue1 = #394887
blue2 = #243373
blue3 = #121C52
blue4 = #08103B
blue5 = #000829
lightBlue1 = #6CE0E0
pink1 = #E86DCB
pink3 = #98559E
blueGrey = #1D1B29
grey5 = #424242
black4 = #1C1C1C
black5 = #000000
foreg = #000000

bg = ${colors.blueGrey}
main = ${colors.pink1}
secondary = ${colors.lightBlue1}

[bar/left]
width = 20%
height = 25
offset-x = 16
offset-y = 4
bottom = true
radius = 0
override-redirect = true
wm-restack = ewmh

border-size = 1
border-color = ${colors.main}
background = ${colors.bg}
foreground = ${colors.main}

font-0 = "FiraMono Nerd Font:size=15"

fixed-center = true

padding = 2
modules-left = date
modules-right = time
#modules-center = date

[bar/center]
width = 25%
height = 25
offset-x = 37.5%
offset-y = 4
bottom = true

radius = 0
# removes i3 anchoring
override-redirect = true
# makes bar sit underneath fullscreen windows
wm-restack = ewmh

border-size = 1
border-color = ${colors.main}
background = ${colors.bg}
foreground = ${colors.main}

font-0 = "FiraMono Nerd Font:size=15"

fixed-center = true

modules-center = i3

[bar/right]
width = 20%
height = 25
offset-x = 1520
offset-y = 4
bottom = true
radius = 0
override-redirect = true
wm-restack = ewmh

border-size = 1
border-color = ${colors.main}
background = ${colors.bg}
foreground = ${colors.main}

font-0 = "FiraMono Nerd Font:size=15"

fixed-center = true

padding = 2
modules-left = date
modules-right = time
[settings]
screenchange-reload = true
pseudo-transparency = false

[module/date]
type = internal/date
interval = 120

date = %B %d

[module/time]
type = internal/date
interval = 60

date = %H:%M
LABEL = %date%

format-foreground = ${colors.main}

[module/i3]
type = internal/i3

enable-click = false
enable-scroll = false
wrapping-scroll = false
strip-wsnumbers = true

#ws-icon-0 = 1;Browse
#ws-icon-1 = 1;♚
#ws-icon-2 = 2;Test1
#ws-icon-3 = 4:Test2
#ws-icon-4 = 5:Test3
#ws-icon-5 = 6:Test4

format = <label-state>

#label-focuse = %index%
#label-focused = %icon%
#label-unfocused = %icon%
#label-visible = %icon%
#label-urgent = %icon%
label-focused = %name%
label-unfocused = %name%
label-visible = %name%
label-urgent = %name%

label-focused-foreground = ${colors.secondary}

label-separator = |
label-separator-padding = 0
label-separator-foreground = #444444
