
[colors]
white = #FFFFFF
whiteYellow = #FFFEE5
blue0 = #7489D4
blue1 = #394887
blue2 = #243373
blue3 = #121C52
blue4 = #08103B
blue5 = #000829
lightBlue1 = #6CE0E0
pink1 = #E86DCB
pink3 = #98559E
blueGrey = #1D1B29
grey5 = #424242
black4 = #1C1C1C
black5 = #000000
foreg = #000000

bg = ${colors.blueGrey}
main = ${colors.pink1}


[bar/main]
width = 25%
height = 25
offset-x = 37.5%
offset-y = 4
bottom = true

radius = 5
# removes i3 anchoring
override-redirect = true

border-size = 1
border-color = ${colors.main}
background = ${colors.bg}
foreground = ${colors.main}

font-0 = "FiraMono Nerd Font:size=15"

fixed-center = true

modules-center = date

modules-left = i3

[settings]
screenchange-reload = true
pseudo-transparency = false

[module/date]
type = internal/date
interval = 60

date = %H:%M
LABEL = %date%

format-foreground = ${colors.main}

[module/i3]
type = internal/i3

enable-click = false
enable-scroll = false
wrapping-scroll = false
strip-wsnumbers = true

format = <label-state>

label-focused = %index%
label-unfocused = %index%
label-visible = %index%
label-urgent = %index%

